name: Feature request
description: Submit a feature request for Stately or XState
title: "[Feature request]: "
labels: ["open"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for sharing a feature request, please add some more details below.
  - type: dropdown
    id: category
    attributes:
      label: Which category is most relevant to your feature request?
      multiple: false
      options:
        - Editor
        - XState
        - Documentation
        - Workflows
        - Devtools
        - Examples
        - Community
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the feature and how it would help you or your team.
      placeholder: Give us more details
    validations:
      required: true