name: Feature request
description: Submit a feature request for Stately or XState
title: "Descriptive title"
labels: ["open"]
body:
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the feature and how it would help you or your team.
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Choose a relevant category for your feature request.
      multiple: false
      options:
        - Editor
        - XState
        - Documentation
        - Workflows
        - Devtools
        - Examples
        - Community